### PR TITLE
board-image/buildroot-sdk-milkv-duos-sd: add 1.1.0

### PR DESCRIPTION
**Pull request by lanthora**

### CODE REVIEW

**Comment by lanthora** [comment]
Is there a way to test whether the manifests are correct before merging into master?

**Comment by xen0n** [comment]
First of all, thank you for your contribution!

You may have to add a DCO (the `Signed-off-by: Your Name <your@email.com>` tag) in the commit message, because this is our first (!) external contribution and we have to ensure proper copyright.

As for manifest checking, you can generate them using the `ruyi admin manifest` subcommand, or manually check by just switching the Ruyi repository location to your local fork (the configuration should be described in `ruyi`'s README) and trying to install the package. There's no magic involved so you should be safe though...

**Comment by lanthora** [comment]
After modifying remote and branch, the new version image was successfully flashed.

```bash
# cat .config/ruyi/config.toml | grep "^remote\|^branch" 
remote = "https://github.com/lanthora/packages-index.git"
branch = "milkv-duos-sd-v1.1.0"

# [root@milkv-duo]~# cat /etc/os-release 
NAME=Buildroot
VERSION=20240410-2151
ID=buildroot
VERSION_ID=2021.05
PRETTY_NAME="Buildroot 2021.05"
```

**Comment by xen0n** [comment]
Triage: the team need to investigate whether the DCO certificate makes anonymous contributions suitable for integration.

**Comment by xen0n** [comment]
The contribution is kind of trivial that cannot create copyright concern for the project, and as such the team has agreed to merge it on a case-by-case basis. We will put up a contribution guideline for the RuyiSDK project as a whole to make all of this explicit and transparent from now on.

Thanks for your contribution!

**Pull request merged**
